### ISSUE TITLE
xml to markdown

### ISSUE THREAD

**Issue by wangsai** [bolechen/phpdoc-zh#1]
是否可以探索一下将 xml 格式的文档转为 markdown 或 mdx 格式，让翻译工作变得更便利，让 php 周边都能与时俱进。

**Comment by shiny** [comment]
中文翻译的要点在于完全同步英文文档，连标记都不能错一点，我认为中文文档不存在发挥空间，除非去推动英文版的改进。

或者可以有谁可以出个翻译互转的技术方案，大家评估下是否可行。😂

**Comment by wangsai** [comment]
从逻辑上讲，首先应该推动英文文档的格式转换。因为英文文档作为其它语言翻译版本的上游，只有英文文档转了格式，其它翻译才好跟进。
但是，从一开始就推动官方做文档格式转换的话，会导致大量工作和协调要做，目前最好的选择是拿英文到中文的翻译作为一个样板，也就是在官方英文文档 xml 格式的基础上转换为 markdown 格式，然后在 markdown 格式的英文文档上进行中文翻译。这一流程只作为中文翻译的内部流程，并不进入官方文档仓库。等实验成功了，再推动官方的改进。

中文文档的目标受众是中文为母语的开发者，并且贡献翻译的也是这一批人。满足这批人的需求和习惯更重要，并且参与贡献的人本来就不多，因为一个老旧的格式和系统阻挡了大家贡献的意愿。

**Comment by shiny** [comment]
恕我直言，我在 PHP 手册中文翻译坚持了八年，也帮助很多人申请了 svn 账号，这么多年来贡献翻译的屈指可数，坚持下来的几乎为零。
我没看到谁能去做这个工作，如果你有心，请从基本的翻译工作做起，熟悉流程，然后谈这些，而不是空谈可行性。目前没有志愿者做这个事情。
